### ISSUE TITLE
当桶的目录中文件大于1000个以上的时候，下载这个目录，一直循环下载下去是什么情况？

### ISSUE THREAD

**Issue by duquanglong** [huaweicloud/huaweicloud-obs-obsutil#2]

**Comment by x00403408** [comment]
麻烦详细提供具体的问题现象描述，当前问题描述不足以判断问题；请按照如下格式进一步反馈其他信息辅助问题定位：
1、调用的完整命令及参数组合；
2、期待的现象及实际执行结果；
3、问题出现的概率：是否每次执行同样的命令该问题场景必现或偶现；
4、如有报错信息，请详细提供报错信息截图；

**Comment by x00403408** [comment]
您好，由于一个月内未收到相关回复，我们将关闭该issue；后续有新的问题请在新的issue中跟踪；
